services:
  python:
    image: python-fastapi:latest
    build:
      context: .
      dockerfile: docker/Dockerfile 
    container_name: python_fastapi
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - python_network

networks:
  python_network: